### ISSUE TITLE
Album Art not loaded on skin startup

### ISSUE THREAD

**Issue by SaruDesu** [sctanf/unplayer#3]
Album art is not loaded in the startup. This can be a bother if you have a music player that starts on windows startup (e.g. Spotify).

I fixed it by adding the `[!Delay 5000][!UpdateMeter AlbumArt][!Redraw]` bangs on OnRefreshAction. It must have a delay so that the command starts after the skin initialization.

`OnRefreshAction=[!CommandMeasure Action1 Run][!DisableMeasure ChkCtrlStyle][!DisableMeasure ChkAlign][!Delay 5000][!UpdateMeter AlbumArt][!Redraw]`

**Comment by sctanf** [comment]
Strangely things are updating out of order. That fix will do but I am going to add some more constant updates to the art measures instead, hopefully that will make it more redundant. Thanks!
